### ISSUE TITLE
Errore getting epg

### ISSUE THREAD

**Issue by aliceanto** [RogerSelwyn/skyq_remote#12]
Hello Roger,
I’m sorry but I don’t know how to contact you in other way. This is not an issue but an help request : I’m trying to call the epg with iOS shortcuts using get data from url but I got an ero or on data format that for me seem ok 
In attach the screenshot of request and the error, could you kindly help me ?? Many thanks

![IMG_2321](https://github.com/RogerSelwyn/skyq_remote/assets/5999930/ff715b8f-28fd-4e1a-afbc-562893ae0461)

**Comment by RogerSelwyn** [comment]
Yep, it is 3/4 digits

**Comment by aliceanto** [comment]
Many Thanks I have found my mistake. And thank for your work for community

**Comment by aliceanto** [comment]
How close the issue ?
