### ISSUE TITLE
cannot import name 'SkyQRemote' from 'pyskyqremote

### ISSUE THREAD

**Issue by Liixee** [RogerSelwyn/skyq_remote#6]
I am just testing the interesting project. When I start, however, I get that it cannot be imported. The installation with pip install has been completed. I've tested it on Debian and Ubuntu.

`lixe@Felix-PC:~$ pip3 install pyskyqremote
Collecting pyskyqremote
  Downloading pyskyqremote-0.2.38-py3-none-any.whl (25 kB)
Collecting requests>=2.24.0
  Downloading requests-2.25.1-py2.py3-none-any.whl (61 kB)
     |████████████████████████████████| 61 kB 2.7 MB/s
Collecting websocket-client>=0.56.0
  Downloading websocket_client-0.58.0-py2.py3-none-any.whl (61 kB)
     |████████████████████████████████| 61 kB 4.9 MB/s
Collecting xmltodict>=0.12.0
  Downloading xmltodict-0.12.0-py2.py3-none-any.whl (9.2 kB)
Collecting pycountry>=20.7.3
  Downloading pycountry-20.7.3.tar.gz (10.1 MB)
     |████████████████████████████████| 10.1 MB 6.1 MB/s
Requirement already satisfied: idna<3,>=2.5 in /usr/lib/python3/dist-packages (from requests>=2.24.0->pyskyqremote) (2.8)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/lib/python3/dist-packages (from requests>=2.24.0->pyskyqremote) (1.25.8)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests>=2.24.0->pyskyqremote) (2019.11.28)
Requirement already satisfied: chardet<5,>=3.0.2 in /usr/lib/python3/dist-packages (from requests>=2.24.0->pyskyqremote) (3.0.4)
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from websocket-client>=0.56.0->pyskyqremote) (1.14.0)
Building wheels for collected packages: pycountry
  Building wheel for pycountry (setup.py) ... done
  Created wheel for pycountry: filename=pycountry-20.7.3-py2.py3-none-any.whl size=10746863 sha256=6636286631f3f1f7a141a418cd10cd5c33a36c076622327b183130516ef2cae5
  Stored in directory: /home/lixe/.cache/pip/wheels/09/eb/0d/4ee773c6a4aadc2a43cb5c1d07f268f13c4cdc0eec88e7c1ef
Successfully built pycountry
Installing collected packages: requests, websocket-client, xmltodict, pycountry, pyskyqremote
Successfully installed pycountry-20.7.3 pyskyqremote-0.2.38 requests-2.25.1 websocket-client-0.58.0 xmltodict-0.12.0`

`lixe@Felix-PC:~$ python3 sky.py
Traceback (most recent call last):
  File "sky.py", line 1, in <module>
    from pyskyqremote import SkyQRemote
ImportError: cannot import name 'SkyQRemote' from 'pyskyqremote' (/home/lixe/.local/lib/python3.8/site-packages/pyskyqremote/__init__.py)
lixe@Felix-PC:~$`

Can you help me?

**Comment by RogerSelwyn** [comment]
I've updated the readme, it should be:-

`from pyskyqremote.skyq_remote import SkyQRemote`

**Comment by RogerSelwyn** [comment]
No further queries, so closing
